### ISSUE TITLE
How to update namespace experiments on the fly

### ISSUE THREAD

**Issue by PaulAlgan** [facebook/planout#109]
I read document but I don't see how to update namespace expriments( number of segment in each experiment). From my understand I have to put class in  `self.add_experiment(exp_name, exp_class, n_segment)` so how to `add_experiment` by `SimpleInterpretedExperiment`

Thank you.

**Comment by eytan** [comment]
Hi @PaulAlgan, I am sorry but I am having difficulty understanding your question.  Perhaps you could give a little bit more context about the specific experiments you are trying to run, and what the current set of APIs don't seem to provide?
