### ISSUE TITLE
No mapping between project git releases/tags and PyPI versions

### ISSUE THREAD

**Issue by omnilinguist** [facebook/planout#112]
There doesn't seem to be a clear way to know at what points on the code correspond to what versions got released to PyPI (for example, see the historic list at https://pypi.python.org/simple/planout/). This could be helpful to enable integrators of the framework to know exactly what code it is that they are using, and is a very common practice.

Could perhaps consider using git releases/tags for this in the future? (Even better would be to retroactively backtag the previous releases, but it's possible that information might have already been lost.) For example: https://github.com/kennethreitz/requests/tags and https://github.com/kennethreitz/requests/releases.

**Comment by eytan** [comment]
Thanks for the tip, we will try to apply this practice when making future changes to the PlanOut reference implementation. cc @kkashin.
