### ISSUE TITLE
Python 3 iteritems call on dictionary throws error

### ISSUE THREAD

**Issue by oguzserbetci** [facebook/planout#117]
Hello, I'm not quite sure if I have something set up wrong or this bug went unnoticed.

I get the following error when I try to remove an experiment from a `namespace`:

```
File "planout/namespace.py", line 152, in remove_experiment
    [s for s, n in self.segment_allocations.iteritems() if n == name]
AttributeError: 'dict' object has no attribute 'iteritems'
```

`setup_experiments` look like this:

```
def setup_experiments(self):
  self.add_experiment('gif', GifExperiment, 50)
  self.add_experiment('noconvo', NoConvoExperiment, 50)
  self.remove_experiment('gif')
```

Am I doing something wrong or should this be fixed by:
- using .items(), or
- using six.iteritems()

**Comment by karlrank** [comment]
Hi. I ran into the same issue, any reason this fix is not moving forward?
