### ISSUE TITLE
Serialized format for Namespaces?

### ISSUE THREAD

**Issue by burin** [facebook/planout#122]
Is there an equivalent to the Planout experiment serialized JSON for namespaces?

Planout4j has [something close](https://github.com/eric239/planout4j/blob/9d71a34e5013a18cfad98cdd5409a8927469931a/compiler/src/test/resources/test_namespace.yaml).

I'm interested in defining and manage namespaces somewhere, and having an interpreter take in some JSON and construct an instance of a namespace (the same way you would create an Experiment instance from JSON).

**Comment by eytan** [comment]
I @burin, no, there isn't.  In general I wouldn't recommend PlanOut4J implementation's namespace implementation.  In particular, there is no reason to store the experiment add and remove operations, as this can get computationally expensive / slow if you run a lot of experiments in the same namespace.

You might be better off using a database or SQLAlchemy to store experiments associated w/ a namespace, and then also store in the db/orm the segment->experiment mapping.

**Comment by burin** [comment]
Thanks @eytan! Thanks for the tip about using something else to manage namespaces/segment mapping. 

I wanted to use the planout namespaces for various reasons (including ability to point to the planout docs), but I guess it only makes sense if you "bake in" the experiment/namespaces in the code, which in my case I wouldn't be doing.
