### ISSUE TITLE
Update link to Golang interpreter under alpha submodule

### ISSUE THREAD

**Issue by tsujeeth** [facebook/planout#150]
The Golang planout repo (originally under URXtech) now resides at:
https://github.com/biased-unit/planout-golang

The library has not seen development for over 2 years now. Contributions / Maintainers welcome! 

@eytan , is there an active Go library out there?

_Originally posted by @tsujeeth in https://github.com/facebook/planout/issues/30#issuecomment-594735711_

**Comment by tsujeeth** [comment]
From @irvifa 
https://github.com/irvifa/planout/commit/c7174926dfc287eb6b42f2fd1dcebb93b8f9698b

**Comment by irvifa** [comment]
Noted, I'll update the travis then..

**Comment by irvifa** [comment]
Creating a PR https://github.com/facebook/planout/pull/152. Can you please also check it? Thanks!
