### ISSUE TITLE
Open sourcing Planout interpreter in Golang

### ISSUE THREAD

**Issue by tsujeeth** [facebook/planout#30]
https://github.com/URXtech/planout-go-interpreter

Hey guys, we (at URX) have implemented a Planout interpreter in Golang. Check it out! Any feedback/suggestion is greatly appreciated.

**Comment by krithika369** [comment]
Hello @eytan, I'm unable to access the Golang submodule under alpha (and can't find the repo on the owner's Github page either). I'm wondering what the status of this development was (I realise this is quite an old thread) and if there are any other active efforts to implement the PlanOut interpreter in Golang, that you may be aware of?

**Comment by irvifa** [comment]
Hello @eytan I also have similar problem there, is this moved as a private repo?

**Comment by tsujeeth** [comment]
The Golang planout repo (originally under URXtech) now resides at:
https://github.com/biased-unit/planout-golang

The library has not seen development for over 2 years now. Contributions / Maintainers welcome! 

@eytan , is there an active Go library out there?

**Comment by irvifa** [comment]
Please see this PR https://github.com/facebook/planout/pull/152 Thanks!
