### ISSUE TITLE
Javascript Version

### ISSUE THREAD

**Issue by eipark** [facebook/planout#40]
Are you aware of any JS versions of Planout, whether fully fleshed out or in flight? Wanted to check before I started an implementation. Thanks!

**Comment by eytan** [comment]
Awesome! I am not aware of any ports.  I was thinking of coding it myself
in Flow, but haven't had the time.  I am about to open-source the
Hack-based interpreter, which is strongly typed, so porting from that
should be fairly straightforward.  Otherwise I would strongly recommend
using ES6 and using a transpiler in with npm.  I would also be happy to
follow along and review intermediate versions of your port if you'd like.

**Comment by eipark** [comment]
Great, thanks. Please throw a note in here when the Hack-based interpreter is out. I'm not sure how much of Planout we'll need at this point - we may just want a very small subset of features/concepts to start. But if we end up needing more and more, I'll start throwing in some PRs/code reviews.

**Comment by eipark** [comment]
What's the minimum subset of stuff required for an impl? Is it just everything minus namespaces? And my choosing of operators?

**Comment by eytan** [comment]
I would say the Experiment object, the Assignment object, and the random assignment operators would be sufficient for running ad-hoc experiments using a native API.  Check out the Ruby port -- it's pretty much as bare bones as you can get, but is still fully functional:
  https://github.com/facebook/planout/tree/master/alpha/ruby

Of course, having the full interpreter would be awesome, but I wouldn't bother with Namespaces.  We are going to completely revamp the namespaces pretty soon anyways.

**Comment by eipark** [comment]
Thanks - would you be able to shed light on some of the expected changes on namespaces? We have a need for them so even what's there now would be useful for us.

**Comment by eytan** [comment]
Basically, the namespace class is overloaded: it both manages and retrieves the experiments.  The stuff that manages the experiments really ought to belong in its own class.  Also, there are various things implemented by SimpleNamespace that should be part of the AbstractNamespace.  For example, addExperiment could be written as part of the abstract base class, and rely on some method called allocateSegments.  See discussion with @akalicki about proposed re-organization at https://github.com/vimeo/ABLincoln/pull/1#discussion_r22338953 and his PR, https://github.com/vimeo/ABLincoln/pull/3.  Note that none of these are fundamental changes to the way stuff works, it's just a matter of cleaning up the code underneath the hood.

**Comment by eipark** [comment]
Got it thanks.

**Comment by eytan** [comment]
btw, you might want to use the 'long' npm module.  AFAIK the PlanOut hashing procedure requires more bits than JS natively supports.

**Comment by eytan** [comment]
@eipark , feel free to throw up whatever you've got in alpha/.  You'd be surprised what other people pick up once you put a little bit of code out there.

**Comment by eipark** [comment]
Will do.

**Comment by eytan** [comment]
See @rawls238's port in alpha/js. It's pretty comprehensive.

**Comment by eipark** [comment]
For anyone who comes across this issue, HubSpot now maintains a [JS port of planout](https://github.com/HubSpot/PlanOut.js), which is linked to on the PlanOut splash page also.
