### ISSUE TITLE
Assignment unaffected when salt set in SimpleNamespace

### ISSUE THREAD

**Issue by akalicki** [facebook/planout#43]
Looks like we might have a bug coming from [line 173](https://github.com/facebook/planout/blob/master/python/planout/namespace.py#L173) in SimpleNamespace - if the Assignment is only generated in the Experiment's constructor, then it will not take into account the extra salt coming from the namespace.

Possible solution: re-set the Assignment's `experiment_salt` member whenever the experiment's salt setter is called?

**Comment by eytan** [comment]
Good catch -- that's exactly the solution I would take.
