### ISSUE TITLE
Discussion of PO java port

### ISSUE THREAD

**Issue by eric239** [facebook/planout#52]
Moving the conversation between @eytan and @eric239 about open-sourcing PO java port here for better tracking.

**Comment by eric239** [comment]
@eytan Sorry couldn't get to work on this over the weekend due to some personal matters. But it's on my list for this week :smile: 

We have a few (hopefully small) logistical challenges to sort out:

- determine which portion of our port should be open-sourced
Our port is a maven-based project consisting of the following modules:
  - `core`
    - `planout ops`: pretty much verbatim port
    - `Namespace` support: here we deviated from the original PO having assumed that in most cases it is more convenient to store namespace configuration in outside of code rather than configure programmatically. To that extent, we built `NamespaceConfiguration` helper class as well as `Namespace` and `Experiment` objects around that model. The former expects a nested dict structure which can be serialized into JSON or YAML (we use the latter). We do *not* support stand-alone (no namespace) experiments.
  - `compiler`: this wraps the JS PO DSL compiler as well as provides helper APIs for parsing YAML and delegates to `NamespaceConfigurationBuilder` from the `core` module above.
  - `config`: this is our internal mechanics of maintaining central repository of the configuration data
  - `client`: this module glues all the previous ones together and exposes a `factory` API for obtaining a `Namespace` instance.
We will certainly expose `core`. I'm inclined to think that `config` and `client` are somewhat specific to our approach to adopting PO. I'm on the fence about `compiler`.

- clean out 3d-party (maven) dependencies, come up with better package naming, and other similar "cleanup for the outside world" items. This is a bit more awkward with java (esp with maven) than with the likes of python/ruby/php. A separate item here is publishing to OSS maven repo so there're binary downloads for those not wanting to build from source.

- need to set up corp acct on github. Once this is done and I do the minimum required cleanup from the point above, I can start pouring in some code for review.

**Comment by eytan** [comment]
This all sounds wonderful, and much closer to the production stack used at Facebook.  This will be a huge contribution to the open-source community.  I would expect that the majority of users of this port will be deploying PlanOut in a production setting, so all of these modifications are quite reasonable, particularly (1) the requirement that all experiments are run within namespaces; (2) having a namespaces depend largely on external storage and configuration (3) for there to be a lot more metadata floating around that needs to be managed.

**Comment by eric239** [comment]
Hey @eytan, one of our toughest "logistic" choices is picking a name that would be sensible outside the our org (the original name played a pun on an internally-built system). To that extent, we seem to like `PlanOut4J` but wanted to check with you if that would be OK with Facebook (e.g. from legal, etc. perspective). Please let me know.

We're progressing, albeit much slower than I anticipated, largely due to this being first official attempt to open-source something that was developed in house.

Thanks!

**Comment by eytan** [comment]
Hi @eric239, I am glad to hear things are moving along!  PlanOut4J, or even simply, 'PlanOut' is fine with us.

**Comment by eytan** [comment]
@eric239, any updates?  We have an emerging use case for doing some experimentation client side (on Android/Java), and could benefit from having a Java-based PlanOut interpreter...

**Comment by eric239** [comment]
Ugh sorry I've been full of broken promises, that wasn't intended at all.
What happened was that we've been chasing a nasty bug that manifested as
oscillation of users between different param values. It turned out that the
internal structure we used to represent compiled planout scripts
(essentially parsed json) was shared, and all planout randoms modify the
structure by replacing `unit` node with result of its evaluation. Needless
to say, in a highly concurrent setup that wrecked havoc. After having fixed
that, we've started running some real experiments in production setting and
so far the outlook is good.

I'm not going to try to make any more promises for fear of once again not
being able to meet them (e.g. due to my employer shifting priorities) but
let's say I'll try my best to push it out now that there's real confidence
the code is robust enough. I will make another update around middle of the
week.

**Comment by eric239** [comment]
@eytan I'm happy to report that *finally* PlanOut4J is out there:
https://github.com/eric239/planout4j

We plan to move to Glassdoor's "org" account shortly.

You'll see some TODOs in the README and some rough edges here and there, but overall I feel the product is in a good shape and we've been using it extensively in production for a few months by now (very slightly different codebase).

We are very excited to make our debut in the OSS world and will be happy to get all and any feedback from you and anybody else in FB or elsewhere.

**Comment by eric239** [comment]
Update: the new home is https://github.com/Glassdoor/planout4j

**Comment by eytan** [comment]
This is really impressive, Ernest.  I will try to give it a closer look
soon... Do you have any pointers to where the logging takes place?  When do
you expect the Redis storage to be ready?

**Comment by eric239** [comment]
Good question about logging, I need to add this to README. But here's a quick summary:

Logging can mean couple things:
* application logging (diagnostics/error messages)
  * that is handled via standard [SLF4J lib](http://www.slf4j.org/)
  * since planout4j is a library designed to be embedded into a larger app, the choice and configuration of slf4j backend (e.g. log4j and the likes) is left to the consuming app
  * tests and cmd-line tools explicitly configure log4j backend with messages going to stdout
* parameter logging
  * this is, unfortunately, something that is very intertwined with internal systems (and thus hasn't made it to the OSS project) but we definitely want to factor it out
  * different consuming apps will likely have different approaches to logging mechanisms (from simple files-based using e.g. SLF4J/Log4J to message queue based using e.g. Kafka), so we're interested in hearing how do others do / want to do it

Redis backend should be ready by next week (my weekend project)

**Comment by eric239** [comment]
@eytan would it be possible to link to PlanOut4J from PlanOut GH page?

**Comment by eytan** [comment]
Ernest, that would be great. Can you send me an email and we can coordinate there? I would also like to create a Java/ submodule in the PlanOut repository, as we did with Vimeo's PHP port...

**Comment by eric239** [comment]
@eytan I cannot email you yet b/c I don't have your email :-)

Mine is `ernest[at]alerweb[dot]com`

**Comment by eytan** [comment]
Hi @eric239 -- can you please add planout4j as a submodule in the root facebook/planout directory (similar to what vimeo did for their php/ port).  perhaps you could call the directory 'java/'.

**Comment by eric239** [comment]
@eytan yes, that would be nice! Please let me know what I can do to that extent.

Going back to our email exchange a week ago or so, I factored the usage instructions out of readme. I believe readme is ok now, please lmk if it still appears too bloated. I still need to work more on the usage file as well as provide code demos. Please let me know if we're ready to link the documentation.

**Comment by eytan** [comment]
That sounds great. I won't have much time to review the docs until the end of the month, but I would be happy to merge in a PR for the submodule (see https://github.com/facebook/planout/commit/0c739b65d8cf2ff309d53b88af61fc3ba03997f5 for an example).

**Comment by rickhull** [comment]
Fixed the link (gh-pages) to Glassdoor's planout4j here: https://github.com/facebook/planout/pull/60
