### ISSUE TITLE
Using PlanOut with a CDN

### ISSUE THREAD

**Issue by antgel** [facebook/planout#72]
Hi,

I'm asking here as I didn't manage to find alternative discussion groups or support channels for PlanOut.  We're looking to revamp our approach to A/B testing, and we are concerned that our use of a CDN can result in caching tests, and our origin not getting the relevant data.  There's a lot to learn in the area, and we're getting there slowly, but for now, we have one basic question - does PlanOut play well with CDNs?

I hope the question is sensible enough, please let me know if I can clarify it / make it sensible.

Antony

**Comment by eytan** [comment]
Hi Antony,
This sounds like a great question... Can you provide us with a little bit
more context about what kinds of experiments you want to run and what
problems you are encountering with CDNs?

**Comment by crazyshot** [comment]
Hi, Eytan,
Basically we would like to be able to run AB-test on pages that are cached with CDN.
Meaning that when user get to the page, it doesn't pass through the server.

Currently we use manual HTML, for every test, usually some group of invisible div's with ids and then switch visibility in JS based on cookie, id or some other population condition, it works great with CDN (all versions exist in same cache all the time), but it becomes less manageable and worst performance with every additional test we run.
Also it makes us having production deployment every time we want to turn off the test or something.

Can you suggest how things can be done easier/better with planout?

**Comment by eytan** [comment]
You may want to check out this example:
  http://blog.trenthauck.com/posts/pelican-plus-planout/

Note that at some point you'll want to log that a cookie was exposed to a condition, so something needs to talk to a server -- @tshauck 's solution is nice in that it does the server side logging in the right way, and also allows you to deliver content via a CDN.  Another idea would be to do the randomization client-side using @rawls238 's PlanOut.js client-side, but then you'd be have to be really careful about making sure you make an async call to the server as soon as you call getParam().

**Comment by crazyshot** [comment]
Thanks, I'll research that.

**Comment by eytan** [comment]
OK, closing out. Let me know if you figure out a solution -- I'd be happy to write it up on the PlanOut site for others that come across similar issues.
