### ISSUE TITLE
Make it easier to enable / disable exposure logging

### ISSUE THREAD

**Issue by eytan** [facebook/planout#73]
The PlanOut language has a `return` construct that allows experimenters to programmatically enable / disable exposure logging.  For example, an experiment in which 20% of the users are eligible and are randomized into A and B can be written as:

```
eligible = bernoulliTrial(p=0.2, unit=userid);
if(!eligible) {
  return false;
}
variant = uniformChoice(choices=['a','b'], unit=userid);
```

However, many users of PlanOut do not use the PlanOut language and instead use a native API.  Modify the PlanOut reference implementation so that that the return value of the assign() method determines logging.  This would involve checking the return value of assign; if it is None (so that no return was triggered), in_experiment should be set to True; otherwise the truthiness of the return value should be used to keep track of the exposures.  These changes might also be integrated into PlanOut.js (cc @rawls238 ) and the Go implementation (cc @tsujeeth)

**Comment by rawls238** [comment]
:+1: to this

**Comment by rawls238** [comment]
My main concern with this is that if we enable it by default then it will break existing PlanOut implementations that use the native API. I wonder if we can have this be "opt-in" in the sense that users would need to explicitly return True or False in order for us to use the return value to determine exposure logging (if None was returned, logging would be done as it previously was).

What do you think of this approach?

**Comment by eytan** [comment]
Hi Guy -- I think we might both be saying the same thing- the proposed change is "opt in".  Presently, there is no reason for existing assign() methods to return any value, since nothing is done with that return value.  In Python, not calling return is the same as return None, so this proposed change would yield the default behavior for pretty much any existing assign method. The same should also hold true for JavaScript (with undefined instead of None).

AFAIK there is no way to programmatically change logging, so making in experiment be true for scripts whose assign methods return None should completely match existing behavior. (Nevertheless we should still make this a big point release to highlight this potentially breaking change).

**Comment by tsujeeth** [comment]
Hi @eytan, Sorry I missed this discussion somehow. The Go version has not implemented exposure logging yet. Going to scope it out as part of [this](https://github.com/URXtech/planout-golang/issues/7) and include this change as part of it. I'll follow up soon.
