### ISSUE TITLE
Create a ProductionExperiment class

### ISSUE THREAD

**Issue by eytan** [facebook/planout#74]
The SimpleExperiment class is designed to make it easy to get up and running with PlanOut but it's not what people should be using for production.  For example, experiments should be able to assert what variables they set, as to ensure the sanity of experiments when calls to the experiment request parameters that are not defined.  This is done at Facebook via a `getParamNames()` method which reads from metadata that gets saved alongside experiments.  While this might be overkill for many simple applications (and so we may not want to make it part of the SimpleExperiment class), it should be strongly encouraged for production scenarios.

This task is for creating a DemoProductionExperiment that includes this additional functionality.

**Comment by eytan** [comment]
cc @rawls238

**Comment by rawls238** [comment]
this seems relatively simple to do. 

My only worry is that for the JS implementation is that I want to keep the library size reasonably small, but we'll see how much larger this will make the library size after it's implemented.
