### ISSUE TITLE
Ruby fix for WeightedChoice did not make it into the Gem

### ISSUE THREAD

**Issue by jbenson-handy** [facebook/planout#84]
```shell
>$ gem install planout
```
Installing PlanOut from the gem seems to be missing this commit: https://github.com/facebook/planout/commit/d3615821a677386041d2fbe023e11d472efcfa6c

cc: @eytan @mohnish

**Comment by mohnish** [comment]
I'm looking into it right now

**Comment by jbenson-handy** [comment]
awesome thanks!

**Comment by mohnish** [comment]
@jbenson-handy The latest version of the `planout` gem (`0.1.2`) should now be available https://rubygems.org/gems/planout/versions/0.1.2

**Comment by mohnish** [comment]
This issue can now be closed.

**Comment by jbenson-handy** [comment]
@mohnish thanks for the fast turnaround!
