### ISSUE TITLE
unit test failures for python reference implementation

### ISSUE THREAD

**Issue by eytan** [facebook/planout#96]
When I try running the unit tests for the Python reference implementation of PlanOut, I get:

```
ebakshy:test ebakshy$ python test_interpreter.py
Traceback (most recent call last):
  File "test_interpreter.py", line 11, in <module>
    from planout.interpreter import Interpreter
  File "//anaconda/lib/python2.7/site-packages/planout/interpreter.py", line 13, in <module>
    Operators.initFactory()
  File "//anaconda/lib/python2.7/site-packages/planout/ops/utils.py", line 26, in initFactory
    "map": core.Map,
AttributeError: 'module' object has no attribute 'Map'
```

@felixonmars , did you ever encounter this issue when you were refactoring things for python3 compatibility?

**Comment by felixonmars** [comment]
No, the Arch package is at 9a47b316aa31024588f063426bbadd8867cdab77 with my python 3 patches, and all unit tests are passing.

**Comment by eytan** [comment]
I figured out the problem: the `import` statements used in https://github.com/facebook/planout/blob/master/python/planout/ops/utils.py#L15 were somehow accessing my PyPI PlanOut 0.5 version, which didn't have the map operator.
