### ISSUE TITLE
Make a release for 0.6.x?

### ISSUE THREAD

**Issue by felixonmars** [facebook/planout#98]
I noticed some version bumps in git master, but the PyPI version is still at 0.5 which was released in 2014. Any chance a new release would be released to bring Python 3 support and more?

**Comment by eytan** [comment]
@felixonmars, I would be happy to push the latest changes (which revolve around extensibility) into PyPI.  My understanding is that your changes made PlanOut Python 3 compatible --- is there some way we should be more formally representing this in the setup.py for PyPI?

**Comment by felixonmars** [comment]
I have opened a PR to add some trove classifiers. BTW, it would be nice to enable Travis on the repo, and enable the Python tests.

**Comment by eytan** [comment]
Thanks for that @felixonmars (again :)... +1 on enabling Travis for Python --- @rawls238 offered to get that going, so I am hoping that we will have a more reasonable testing process in place soon.

**Comment by felixonmars** [comment]
Thank you. Looking forward to a new release then :)

**Comment by eytan** [comment]
https://pypi.python.org/pypi/PlanOut/0.6.0
